### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by meistroburger** [Jaysigx/Drawbridge#1]
Hi,

The script works (mostly). For the traffic I've used:

```
-- Define global variables for speed zones and their corresponding coordinates
local speedZones = {nil, nil, nil, nil}
local trafficStops = {
    vector3(364.9, -2343.92, 10.9),
    vector3(342.08, -2343.91, 11.22),
    vector3(342.18, -2287.83, 11.21),
    vector3(365.03, -2287.84, 10.84)
}

-- Function to stop traffic at all zones
function StopAllTraffic()
    for i, center in ipairs(trafficStops) do
        if speedZones[i] == nil then
            local radius = 30.0
            speedZones[i] = AddSpeedZoneForCoord(center.x, center.y, center.z, radius, 0.0, false)
        end
    end
    print("All traffic zones have been stopped.")
end

-- Function to start traffic at all zones
function StartAllTraffic()
    for i = 1, #speedZones do
        if speedZones[i] ~= nil then
            RemoveSpeedZone(speedZones[i])
            speedZones[i] = nil
        end
    end
    print("Traffic has resumed in all zones.")
end

-- Register event to stop traffic in all zones
RegisterNetEvent("Bridge:StopAllTraffic")
AddEventHandler("Bridge:StopAllTraffic", StopAllTraffic)

-- Register event to start traffic in all zones
RegisterNetEvent("Bridge:StartAllTraffic")
AddEventHandler("Bridge:StartAllTraffic", StartAllTraffic)
```
But the opening/closing of the bridge is not synced. It would be great if it could be synced between players. Now it loads the model of the bridge for every player that joins, so it needs to have "DoesEntityExists" or something, and than sync the current state.

Would be glad to help you with some stuff.

**Comment by Jaysigx** [comment]
on it boss

**Comment by Jaysigx** [comment]
try the syncing, next bit imma work on is the traffic zone like you have it here, if you look at cl_trafficlights.lua
if you want to make a pull request your most welcome, if not ill get it done anyways.

<3

**Comment by talonlzr** [comment]
I wrote some basic "full event sync'ing" into the latest accepted commit. Try it out and issue a "/bridgeSequence" to send an event to the server to start the synchronized process for everyone.

**Comment by Jaysigx** [comment]
i think this is resolved
